//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.CONTROL_PAGO = new HashSet<CONTROL_PAGO>();
            this.HETRAXEMPLEADO = new HashSet<HETRAXEMPLEADO>();
            this.NOMINA = new HashSet<NOMINA>();
            this.PARAXEMPLE = new HashSet<PARAXEMPLE>();
        }
    
        public int ID_Emple { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Tipo_Documento { get; set; }
        public Nullable<int> Numero_Documento { get; set; }
        public Nullable<int> ID_Cargos { get; set; }
        public Nullable<int> ID_Vinculacion { get; set; }
        public Nullable<int> ID_Horario { get; set; }
        public string Estado { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_PAGO> CONTROL_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HETRAXEMPLEADO> HETRAXEMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOMINA> NOMINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAXEMPLE> PARAXEMPLE { get; set; }
        public virtual HORARIO HORARIO { get; set; }
        public virtual TIPO_VINCULACION TIPO_VINCULACION { get; set; }
    }
}
