//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAXEMPLE
    {
        public int ID_PAEM { get; set; }
        public Nullable<int> ID_Parafiscales { get; set; }
        public Nullable<int> ID_EmpleP { get; set; }
        public string Mes { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual PARAFISCALES PARAFISCALES { get; set; }
    }
}
