//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPro.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAFISCALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARAFISCALES()
        {
            this.PARAXEMPLE = new HashSet<PARAXEMPLE>();
        }
    
        public int ID_Parafiscales { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAXEMPLE> PARAXEMPLE { get; set; }
    }
}
